import type { AbandonedCart } from '../types';

/** Epoch ms N minutes before "now". Carts are seeded relative to module
 * load time, same approach Vastra uses for delivery dates — fine for a demo
 * that's opened and walked through in one sitting; the "abandoned 5 minutes
 * ago" cart (CART-006) stays inside the 15-minute too-recent window for the
 * first 15 minutes of any session, which comfortably covers a live call. */
function minutesAgo(n: number): number {
  return Date.now() - n * 60 * 1000;
}

function hoursAgo(n: number): number {
  return minutesAgo(n * 60);
}

function daysAgo(n: number): number {
  return hoursAgo(n * 24);
}

/**
 * 16 seeded abandoned carts. Edge cases, referenced by id in scenarios.ts:
 *  - CART-005: item already on sale -> no discount permitted
 *  - CART-003: ₹12,999 cart -> top discount tier
 *  - CART-004: single ₹699 item -> lowest tier
 *  - CART-006: abandoned 5 minutes ago -> too recent to discount
 *  - CART-002: multi-item cart
 *  - CART-007: item now out of stock -> cannot be recovered as-is
 *  - CART-013: item not on sale, but a different item in the same category
 *    genuinely is -> agent should surface that instead of a fresh discount
 *  - CART-014: item's own size (L) is out of stock -> fit-objection /
 *    size-unavailable alternative path
 *  - CART-015: customer states an explicit budget -> budget-aware alternative
 *  - CART-016: customer dislikes the item's colour -> colour-aware alternative
 *
 * Opening messages are authored here, not generated by the model — see
 * systemPrompt.ts for why. Each names the actual item and gives one
 * concrete, honest reason to act; none use fake urgency.
 *
 * CART-104 onward are the two newer profile-driven campaign triggers
 * (recommendation, browse-abandonment) — see data/customers.ts for the
 * purchase/browse history each one's opening message and eligibility are
 * actually grounded in. (A third trigger, replenishment, was built and
 * then deliberately removed — see types.ts's CampaignType doc — which is
 * why numbering here starts at 104, not 101.) Same AbandonedCart
 * shape, same state machine (outcome, checkoutLink, discountOffered/etc),
 * just tagged with a non-'cart_recovery' campaignType — see
 * types.ts's CampaignType for why this is a tag, not a parallel data model.
 * `items` here isn't something the customer put in a cart; it's the
 * item the outreach is actually about (the reorder, the recommendation, the
 * browsed product) — resolveCart/checkDiscountEligibility/
 * createCheckoutLinkTool all work against it exactly the same way either way.
 */
export const carts: AbandonedCart[] = [
  {
    cartId: 'CART-001',
    campaignType: 'cart_recovery',
    customerId: '9845011234',
    customerName: 'Ananya Iyer',
    phone: '9845011234',
    city: 'Bengaluru',
    items: [{ itemId: 'K-KUR-01', size: 'M', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: daysAgo(2),
    openingMessage:
      "Hi Ananya, it's Meera from Kora 🌿 You left the Undyed Cotton Straight Kurta in your cart — just checking, was it the size or something else that made you pause? Happy to help if you had questions.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-002',
    campaignType: 'cart_recovery',
    customerId: '9845022345',
    customerName: 'Priya Nair',
    phone: '9845022345',
    city: 'Kochi',
    items: [
      { itemId: 'K-CO-01', size: 'S', colour: 'Undyed Natural', quantity: 1 },
      { itemId: 'K-TOP-01', size: 'S', colour: 'Sage', quantity: 1 },
    ],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Priya, Meera here from Kora. You had the Undyed Cotton Co-ord Set and the Sage Wrap Top saved together — they're actually from the same collection and pair well if you wanted to wear them separately too. Want me to hold them for you?",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-003',
    campaignType: 'cart_recovery',
    customerId: '9845033456',
    customerName: 'Rohan Mehta',
    phone: '9845033456',
    city: 'Mumbai',
    items: [{ itemId: 'K-SET-01', size: 'L', colour: 'Ivory', quantity: 1 }],
    abandonedAt: daysAgo(3),
    openingMessage:
      "Hi Rohan, it's Meera from Kora. The Bridal Handloom Silk Set you were looking at is one of our most requested occasion pieces this season — each one is hand-finished so we only hold small batches. Wanted to check if you had any questions before it moves out of stock in your size.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-004',
    campaignType: 'cart_recovery',
    customerId: '9845044567',
    customerName: 'Kavya Reddy',
    phone: '9845044567',
    city: 'Hyderabad',
    items: [{ itemId: 'K-TOP-02', size: 'M', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: hoursAgo(6),
    openingMessage:
      "Hi Kavya, Meera from Kora here. Just noticed the Undyed Cotton Boxy Top is still sitting in your cart — it's one of our simplest everyday pieces. Let me know if you'd like a hand finishing the order.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-005',
    campaignType: 'cart_recovery',
    customerId: '9845055678',
    customerName: 'Simran Kaur',
    phone: '9845055678',
    city: 'Chandigarh',
    items: [{ itemId: 'K-DRS-01', size: 'M', colour: 'Clay', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Simran, it's Meera from Kora. Good timing actually — the Clay Hand Block-Print Midi Dress you saved is already marked down for this week. Wanted to flag it in case the price was what gave you pause.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-006',
    campaignType: 'cart_recovery',
    customerId: '9845066789',
    customerName: 'Aditi Deshmukh',
    phone: '9845066789',
    city: 'Pune',
    items: [{ itemId: 'K-KUR-02', size: 'L', colour: 'Sage', quantity: 1 }],
    abandonedAt: minutesAgo(5),
    openingMessage:
      "Hi Aditi, Meera here from Kora 🌿 Saw you were just looking at the Sage Linen A-Line Kurta — let me know if you had any sizing questions, happy to help before you head out.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-007',
    campaignType: 'cart_recovery',
    customerId: '9845077890',
    customerName: 'Devika Menon',
    phone: '9845077890',
    city: 'Kozhikode',
    items: [{ itemId: 'K-CO-02', size: 'M', colour: 'Sage', quantity: 1 }],
    abandonedAt: hoursAgo(4),
    openingMessage:
      "Hi Devika, it's Meera from Kora. You had the Sage Linen Co-ord Set in your cart — wanted to check in and see if you had any questions about it before you decide.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-008',
    campaignType: 'cart_recovery',
    customerId: '9845088901',
    customerName: 'Farah Sheikh',
    phone: '9845088901',
    city: 'Ahmedabad',
    items: [{ itemId: 'K-DRS-03', size: 'M', colour: 'Ivory', quantity: 1 }],
    abandonedAt: daysAgo(2),
    openingMessage:
      "Hi Farah, Meera from Kora here. The Limited Edition Hand-Embroidered Dress you saved is one of our small-batch pieces — the embroidery is entirely hand-done, which is part of why we only make a few each run. Let me know if you have questions.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-009',
    campaignType: 'cart_recovery',
    customerId: '9845099012',
    customerName: 'Meenakshi Subramaniam',
    phone: '9845099012',
    city: 'Chennai',
    items: [{ itemId: 'K-SAR-01', size: 'Free Size', colour: 'Clay Border', quantity: 1 }],
    abandonedAt: hoursAgo(12),
    openingMessage:
      "Hi Meenakshi, it's Meera from Kora. The Handloom Cotton Saree with the clay border that you saved is woven by a small collective we work with in Karnataka — just wanted to check in before it goes back into general stock.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-010',
    campaignType: 'cart_recovery',
    customerId: '9845100123',
    customerName: 'Ishaan Kapoor',
    phone: '9845100123',
    city: 'Jaipur',
    items: [{ itemId: 'K-TRS-01', size: '32', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Ishaan, Meera here from Kora. You left the Undyed Cotton Wide-Leg Trousers in your cart — no pressure at all, just wanted to say hi in case you had any questions about fit or fabric.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-011',
    campaignType: 'cart_recovery',
    customerId: '9845111234',
    customerName: 'Nandini Rao',
    phone: '9845111234',
    city: 'Coimbatore',
    items: [{ itemId: 'K-SAR-02', size: 'Free Size', colour: 'Sage', quantity: 1 }],
    abandonedAt: daysAgo(2),
    openingMessage:
      "Hi Nandini, it's Meera from Kora. The Sage Tussar Silk Saree you were looking at is still saved in your cart — let me know if I can help with anything, like styling or blouse pairing suggestions.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-012',
    campaignType: 'cart_recovery',
    customerId: '9845122345',
    customerName: 'Vikram Malhotra',
    phone: '9845122345',
    city: 'Lucknow',
    items: [{ itemId: 'K-SHW-01', size: 'Free Size', colour: 'Clay', quantity: 1 }],
    abandonedAt: daysAgo(3),
    openingMessage:
      "Hi Vikram, Meera from Kora here. Just checking in about the Clay Handwoven Cotton Shawl you saved — it's handwoven by artisans we work with directly, so happy to answer anything about it if that's what held you back.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-013',
    campaignType: 'cart_recovery',
    customerId: '9845133456',
    customerName: 'Ritu Bansal',
    phone: '9845133456',
    city: 'Indore',
    items: [{ itemId: 'K-DRS-02', size: 'M', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Ritu, it's Meera from Kora. You left the Undyed Cotton Tiered Maxi Dress in your cart — happy to help with sizing or fabric questions if that's what gave you pause.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-014',
    campaignType: 'cart_recovery',
    customerId: '9845144567',
    customerName: 'Karan Mehra',
    phone: '9845144567',
    city: 'Nagpur',
    items: [{ itemId: 'K-KUR-01', size: 'L', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: hoursAgo(8),
    openingMessage:
      "Hi Karan, Meera here from Kora. Saw you were looking at the Undyed Cotton Straight Kurta — let me know if you had any questions on sizing, happy to help.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-015',
    campaignType: 'cart_recovery',
    customerId: '9845155678',
    customerName: 'Sneha Joshi',
    phone: '9845155678',
    city: 'Surat',
    items: [{ itemId: 'K-TRS-02', size: '30', colour: 'Sage', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Sneha, it's Meera from Kora. You left the Sage Linen Tapered Trousers in your cart — let me know if you had any questions about fit or fabric before deciding.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-016',
    campaignType: 'cart_recovery',
    customerId: '9845166789',
    customerName: 'Arjun Nair',
    phone: '9845166789',
    city: 'Bhopal',
    items: [{ itemId: 'K-KUR-03', size: 'M', colour: 'Clay', quantity: 1 }],
    abandonedAt: daysAgo(2),
    openingMessage:
      "Hi Arjun, Meera from Kora here. You saved the Clay Block-Print Short Kurta — happy to help if the fit, fabric, or anything else about it was on your mind.",
    outcome: 'active',
    discountOffered: false,
  },

  // -----------------------------------------------------------------
  // RECOMMENDATIONS — the suggested item is a real complement to a real
  // past purchase, filtered to size profile + spend band. See
  // tools.ts's getRecommendationsFromHistoryTool.
  // -----------------------------------------------------------------
  {
    cartId: 'CART-104',
    campaignType: 'recommendation',
    customerId: '9845099007',
    customerName: 'Diya Kapoor',
    phone: '9845099007',
    city: 'Bengaluru',
    items: [{ itemId: 'K-TRS-01', size: '32', colour: 'Undyed Natural', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Diya, it's Meera from Kora 🌿 Since you picked up the Undyed Cotton Straight Kurta a few weeks back — the Undyed Cotton Wide-Leg Trousers are from the same undyed line and pair really well with it. Want me to send them over?",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-105',
    campaignType: 'recommendation',
    customerId: '9845099008',
    customerName: 'Farah Qureshi',
    phone: '9845099008',
    city: 'Ahmedabad',
    items: [{ itemId: 'K-SHW-01', size: 'Free Size', colour: 'Clay', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Farah, it's Meera from Kora 🌿 Since you picked up the Undyed Cotton Boxy Top last month — the Clay Handwoven Cotton Shawl layers really nicely over it and felt like a natural next pick. Want me to send it your way?",
    outcome: 'active',
    discountOffered: false,
  },

  // -----------------------------------------------------------------
  // BROWSE-ABANDONMENT — light touch on purpose: never "we noticed you
  // looking", always framed around the product itself. See
  // tools.ts's getBrowseAbandonmentTool and systemPrompt.ts's tone rule.
  // -----------------------------------------------------------------
  {
    cartId: 'CART-106',
    campaignType: 'browse_abandonment',
    customerId: '9845099005',
    customerName: 'Meher Khanna',
    phone: '9845099005',
    city: 'Mumbai',
    items: [{ itemId: 'K-DRS-01', size: 'M', colour: 'Clay', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Meher, it's Meera from Kora 🌿 The Clay Hand Block-Print Midi Dress has been one of our most-loved block prints this season — happy to help with sizing or fabric questions if that's on your mind.",
    outcome: 'active',
    discountOffered: false,
  },
  {
    cartId: 'CART-107',
    campaignType: 'browse_abandonment',
    customerId: '9845099009',
    customerName: 'Ira Sethi',
    phone: '9845099009',
    city: 'Chennai',
    items: [{ itemId: 'K-SAR-02', size: 'Free Size', colour: 'Sage', quantity: 1 }],
    abandonedAt: daysAgo(1),
    openingMessage:
      "Hi Ira, it's Meera from Kora 🌿 The Sage Tussar Silk Saree is one of our most-asked-about pieces this month — happy to help with anything, styling or blouse pairing included.",
    outcome: 'active',
    discountOffered: false,
  },
];

export function getCart(cartId: string): AbandonedCart | undefined {
  return carts.find((c) => c.cartId === cartId);
}
